on:
  push:
    branches:
    - main

name: Build and Deploy

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    if: github.actor == github.event.repository.owner.login
    steps:
    - name: 'Checkout repo'
      uses: actions/checkout@master

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push to GitHub Container Registry
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        cache-from: type=registry,ref=ghcr.io/${{ github.actor }}/discord-poll-bot:latest
        cache-to: type=inline
        tags: |
          ghcr.io/${{ github.actor }}/discord-poll-bot:latest
          ghcr.io/${{ github.actor }}/discord-poll-bot:${{ github.sha }}
