on:
  push:
    branches:
    - master
name: Build and Deploy

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout repo'
      uses: actions/checkout@master

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }}

    - name: Build and push to GitHub Container Registry
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/discord-poll-bot:latest
        cache-to: type=inline
        tags: |
          ghcr.io/${{ github.repository_owner }}/discord-poll-bot:latest
          ghcr.io/${{ github.repository_owner }}/discord-poll-bot:${{ github.sha }}

    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: 'Deploy to Azure Container Instances'
      uses: azure/aci-deploy@v1
      with:
        resource-group: ${{ secrets.RESOURCE_GROUP }}
        dns-name-label: ${{ secrets.RESOURCE_GROUP }}${{ github.run_number }}
        image: ghcr.io/${{ github.repository_owner }}/discord-poll-bot:${{ github.sha }}
        name: discord-poll-bot
        location: 'west us 2'
        secure-environment-variables: DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }}
        memory: 0.5
        cpu: 1
