on:
  push:
    branches:
    - master
name: Build and Deploy

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout repo'
      uses: actions/checkout@master

    - name: Determine image name
      id: image-name
      run: |
        REPOSITORY_LOWER=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
        echo "::set-output name=IMAGE_NAME::$REPOSITORY_LOWER/discord-poll-bot"

    - name: Build and push to GitHub Packages
      uses: docker/build-push-action@v1
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
        repository: ${{ steps.image-name.outputs.IMAGE_NAME }}
        tag_with_ref: true

    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: 'Deploy to Azure Container Instances'
      uses: azure/aci-deploy@v1
      with:
        resource-group: ${{ secrets.RESOURCE_GROUP }}
        dns-name-label: ${{ secrets.RESOURCE_GROUP }}${{ github.run_number }}
        image: docker.pkg.github.com/${{ steps.image-name.outputs.IMAGE_NAME }}:latest
        registry-login-server: docker.pkg.github.com
        registry-username: ${{ github.actor }}
        registry-password: ${{ secrets.GITHUB_TOKEN }}
        name: discord-poll-bot
        location: 'west us'
        secure-environment-variables: DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }}
        memory: 0.5
        cpu: 1
